<?php
/**
 * Created by PhpStorm.
 * User: Ignatenkov Nikita
 * Site: http://ignatenkovnikita.ru/
 * Date: 16.05.2016
 * Time: 18:14
 */

namespace ignatenkovnikita\gsminfo;


use GuzzleHttp\Client;
use yii\base\Component;

class ClientGsmInfo extends Component
{

    /** @var  Client $_client */
    private $_client;

    public $url;
    public $user;
    public $pass;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_client = new Client(['base_uri' => $this->url]);
    }

    private function _send($method, $url)
    {
        return $this->_client->request($method, $url, ['auth' => [$this->user, $this->pass], 'verify' => false]);
    }

    public function getInfo($msisdn)
    {
        $request = $this->_send('GET', $msisdn);

        $obj = json_decode($request->getBody());
        return $obj;
    }

    public function getRegion($msisdn){
        $info = $this->getInfo($msisdn);

        if(!empty($info) && $info->region->name){
            return $info->region->name;
        }
        return null;
    }

}